Vagrant.configure("2") do |config|
  config.vm.box = "centos/6"
  config.vm.network "private_network", ip: "192.168.33.21"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "256"
  end

  #Copy SSH key and inventory files to VM.
  #Ref https://www.vagrantup.com/docs/provisioning/file.html
  config.vm.provision "file", source: "../../ansible/ssh_keys/ansible_ssh_key.pub", destination: "$HOME/.ssh/ansible_ssh_key.pub"

  #Disable default synced folder to avoid rsync errors on Windows hosts.
  #Ref: https://blog.centos.org/2020/05/updated-centos-vagrant-images-available-v2004-01/
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "shell", inline: <<-SHELL

    #This is needed as this image has SELinux enforced, which causes Python modules to fail validation.
    yum -y install libselinux-python

    su - vagrant -c 'cat "$HOME/.ssh/ansible_ssh_key.pub" >> $HOME/.ssh/authorized_keys'

  SHELL
end
