# @author: Helvecio Neto <hfneto@br.ibm.com>
# @copyright: (C) Copyright IBM Corp. 2020. All Rights Reserved.
# @description: This playbook runs and prints the output structure of a module.
# @base_version: 2.7.11
---
- name: File Module
  hosts: '{{ affected_host }}'
  gather_facts: no
  ignore_unreachable: yes

  tasks:
  - name: Create Test Directory
    file:
      path: /tmp/testdir
      state: directory
    register: directory

  - name: Create Test File
    file:
      path: /tmp/testdir/testfile
      state: touch #Creates file if doesn't exist.
      mode: 0600 #Set permission to owner-only.
    register: file

  - name: Print Test File
    debug:
      msg: '{{ file }}'
