# @author: Helvecio Neto <hfneto@br.ibm.com>
# @copyright: (C) Copyright IBM Corp. 2020. All Rights Reserved.
# @description: This playbook runs and prints the output structure of a module.
# @base_version: 2.7.11
---
- name: Ping Module
  hosts: '{{ affected_host }}'
  gather_facts: no
  ignore_unreachable: yes

  tasks:
  - name: Run Ping Module
    ping:
    register: ping

  - name: Ping Module Output
    debug:
      msg: '{{ ping }}'
