# @author: Helvecio Neto <hfneto@br.ibm.com>
# @copyright: (C) Copyright IBM Corp. 2020. All Rights Reserved.
# @description: This file calls tasks for the role "windows".
# @base_version: 2.7.11
- name: Get Powershell Version
  win_shell: $PSVersionTable
  changed_when: false
  register: powershell_version

- name: Get Memory Usage
  script: ../scripts/windows/get_memory_pct.ps1
  register: memory_pct

- name: Save Results To Email Body
  set_fact:
      email:
        from: '{{ windows.email.from }}'
        to: '{{ windows.email.to }}'
        subject: '{{ windows.email.subject }}'
        body: |
          {{ windows.email.subject }}:
          {{ powershell_version.stdout }}
          {{ memory_pct.stdout }}
